### ISSUE TITLE
Multi line "import" not well commented

### ISSUE THREAD

**Issue by darul75** [google/clasp#580]
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

## Expected Behavior

when executing "clasp push" command, following multi line `import` 

```
import {           
    dependency1,            
    dependency2
} from './dep';
```

should be transpiled to

```
//import {           
//    dependency1,            
//    dependency2
//} from './dep';
```

## Actual Behavior

```
import {           
    dependency1,            
    dependency2
} from './dep';
```

is transpiled  to

```
//import {           
\n    dependency1,            
    dependency2
} from './dep';
```                                          

## Steps to Reproduce the Problem

1.
1.

## Specifications

- Node version (`node -v`):
- Version (`clasp -v`):
- OS (Mac/Linux/Windows):

**Comment by takanakahiko** [comment]
This is a problem of `ts2gas` and solved in https://github.com/grant/ts2gas/pull/30 .
It will be fixed in the next version upgrade.

See also: 
https://github.com/grant/ts2gas/issues/29
https://github.com/google/clasp/issues/568

**Comment by darul75** [comment]
ok great, I was reported it just in case and was pretty sure was caused by ts2gas and not clasp, thanks guys.

**Comment by PopGoesTheWza** [comment]
We need @grant or someone else to republish @google/clasp npm package with updated `package.json` which allows update of ts2gas dependency...

**Comment by grant** [comment]
@PopGoesTheWza Published clasp.
LMK if I can do anything else.

**Comment by PopGoesTheWza** [comment]
@darul75 please update clasp to latest version, verify that `ts2gas` got updated to ^1.6.1 and report if issue is solved.

**Comment by darul75** [comment]
We will bump the version but not before 2 weeks and I will let you know how it goes.

**Comment by takanakahiko** [comment]
I think it is okay to close this issue because it is fixed.

**Comment by ardent42c** [comment]
This is still happening with ts2gas 3.6.1 and clasp 2.3.0 ! was the fix rolled back??
Clasp prints out the error of the gs file, but since it doesn't actually let me see the produced gs files, Its hard to figure it out.
