### ISSUE TITLE
(node:17396) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by JeanRemiDelteil** [google/clasp#657]
## Expected Behavior
No deprecation warrning when using `clasp push`

## Actual Behavior
when using `clasp push` we have a deprecation warrning on Node v12.3.1
```
(node:17396) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
```

## Steps to Reproduce the Problem

1. update Node to the current version (12.x)
2. use `clasp push` in a project

## Specifications

- Node version (`node -v`): v12.3.1
- Version (`clasp -v`): 2.1.0
- OS (Mac/Linux/Windows): Windows10

**Comment by PopGoesTheWza** [comment]
@JeanRemiDelteil just to be certain, this issue occurs with the latest `npm`? Have you tried using a local build from the current `master` of this repository?

**Comment by PopGoesTheWza** [comment]
For reference: [DEP0066: OutgoingMessage.prototype._headers, OutgoingMessage.prototype._headerNames](https://nodejs.org/api/deprecations.html#deprecations_dep0066_outgoingmessage_prototype_headers_outgoingmessage_prototype_headernames)

@JeanRemiDelteil @grant I was able to reproduce this issue on Mac OS, using Node 12.3.1 and clasp@2.1.0
I then used a local build from this repository and the deprecation warning no longer occured.

This issue is likely to be closed with next release of clasp.

**Comment by JeanRemiDelteil** [comment]
Great !

**Comment by grant** [comment]
Note: I've published `@google/clasp@2.2`

**Comment by koconnor3** [comment]
any updates on this? I'm still seeing "(node:...) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated"

**Comment by PopGoesTheWza** [comment]
@koconnor3 what version of nodejs and clasp are you using?

**Comment by koconnor3** [comment]
> @koconnor3 what version of nodejs and clasp are you using?

my bad, looks like I had only updated clasp on my _other_ machine 🤦‍♂️
