### ISSUE TITLE
clasp push hangs

### ISSUE THREAD

**Issue by nmccready** [google/clasp#66]
## Expected Behavior
Times out and or have a debugging capability from #65  to figure out why it is hanging.

## Actual Behavior
```
❯ clasp push
\ Pushing files...   

```
Goes on forever

**Comment by nmccready** [comment]
The error was due to a file not existing ENOENT within the node_modules directory. The error is basically getting swallowed by `logError` around line 633.

```
                            recursive(rootDir || path.join('.', '/'), function (err, filePaths) {
                                console.log('recursive');
                                console.log({filePaths});
                                console.log({err});  // ENOENT error is truthy, thus hitting logError
                                if (err)
                                    return logError(err);
```

**Comment by nmccready** [comment]
So it gets eaten up here https://github.com/google/clasp/blob/master/index.ts#L595 .

**Comment by grant** [comment]
To actually take on this issue, I'll need more details around what files are being pushed so I can reproduce this error.

**Comment by grant** [comment]
I'm going to close this as it might be outdated and there's not a great way to reproduce the error.
I think `.claspignore` wasn't implemented at this point and could prevent this problem.

Ping here if you see this issue (and please provide repro steps).

**Comment by redbar0n** [comment]
I just got this bug when I tried `clasp push` having a `.claspignore` file in my repo. But deleting the `.claspignore` file made it work again.

**Comment by vdavid** [comment]
It's two years later, and I'm experiencing the same as @redbar0n. @grant, might be worth reopening this?

**Comment by grant** [comment]
Hey @vdavid , I don't work on this anymore, so it's probably best to not @ me.

Maybe your issue was fixed with https://github.com/google/clasp/pull/936.

I'd recommend stating your version. If less than v2.4.2, upgrade.

**Comment by vdavid** [comment]
@sqrrrl perhaps? This problem seems to affect the latest version of Clasp.

**Comment by vdavid** [comment]
Still the same. More info:
- Latest Clasp (2.4.2)
- Latest MacOS (13.1)
- TyepScript
- `clasp push -f` doesn't solve it
- Removing `.claspignore` solves it, but then I need to delete most of the uploaded *.gs files manually, one by one, otherwise the script fails.

Would be cool if this could be solved.

**Comment by vdavid** [comment]
Maybe @PopGoesTheWza is the one to mention here?

**Comment by vdavid** [comment]
Okay, so I've found the problem and a solution!

_Technically_, it's not true that Clasp hangs if the `.claspignore` file is specified. What happens is that `.claspignore` directly overwrites the default ignore pattern, and in my case, it pulled in a whole `node_modules` folder, which was 20k files, and it took longer than a few hours to process all that.

The default ignore pattern is here: https://github.com/google/clasp/blob/master/src/dotfile.ts#L39

A solution is to add this snippet to the top of the custom `.claspignore` file:

```
# ignore all files…
**/**

# except the extensions…
!appsscript.json
!**/*.gs
!**/*.js
!**/*.ts
!**/*.html

# ignore even valid files if in…
.git/**
node_modules/**

# also ignore these:
# TODO: list your files
```

In my case, this solved the problem. I hope it helps others as well.

For Clasp, I think a great solution would be to provide this as a default `.claspignore` option in the docs, and emphasize that without it, no files are ignored by default.
